--
-- Roles
--

-- DB-import etc. via python
CREATE ROLE admin;
ALTER ROLE admin WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '[md5-pwd]';
-- PostgREST
CREATE ROLE authenticator;
ALTER ROLE authenticator WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '[md5-pwd]';
CREATE ROLE web_anon;
ALTER ROLE web_anon WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS PASSWORD '[md5-pwd]';
-- IPT
CREATE ROLE sbdi;
ALTER ROLE sbdi WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '[md5-pwd]';

--
-- Role memberships
--

GRANT admin TO authenticator GRANTED BY postgres;
GRANT web_anon TO authenticator GRANTED BY postgres;
