--
-- Environment variables
--

\set passwd `echo ${POSTGRES_PASSWORD}`
\set anon `echo ${PGRST_DB_ANON_ROLE:-web_anon}`
\set anonpass `echo ${PGRST_DB_ANON_PASS}`

--
-- Roles
--

-- PostgREST
CREATE ROLE authenticator;
ALTER ROLE authenticator WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD :'passwd';
CREATE ROLE :anon;
ALTER ROLE :anon WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS PASSWORD :'anonpass';

--
-- Role memberships
--

GRANT :anon TO authenticator;

GRANT USAGE ON SCHEMA api TO :anon;

GRANT SELECT ON ALL TABLES IN SCHEMA api TO :anon;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA api TO :anon;
GRANT ALL ON ALL TABLES IN SCHEMA api TO authenticator;
